name: release Windows x86

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string

permissions:
  contents: write
  actions: read

jobs:
  release-x86:
    name: sign and upload windows x86
    if: inputs.release_tag != ''
    strategy:
      fail-fast: false
      matrix:
        flavor: [wpf, desktop]
    uses: ./.github/workflows/upload-sign.yml
    with:
      release_tag: ${{ inputs.release_tag }}
      artifact_name: release-windows-x86-${{ matrix.flavor }}
      file_pattern: '*.zip'
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
