name: release macOS

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
    - master

permissions:
  contents: write
  actions: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      target: macos

  release-zip:
    if: inputs.release_tag != ''
    needs: build
    uses: ./.github/workflows/package-zip.yml
    with:
      target: macos
      release_tag: ${{ inputs.release_tag }}
    secrets: inherit

  release-dmg:
    name: sign and upload macOS dmg
    if: inputs.release_tag != ''
    strategy:
      matrix:
        arch: [x64, arm64]
    uses: ./.github/workflows/upload-sign.yml
    with:
      release_tag: ${{ inputs.release_tag }}
      artifact_name: release-dmg-${{ matrix.arch }}
      file_pattern: '*.dmg'
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
